### ISSUE TITLE
Motivation behind github/ organization and docker/python?

### ISSUE THREAD

**Issue by ahatzz11** [github/stale-repos#19]
This is more of a general question than an issue, but I'm curious why this lives in `github/` instead of `actions/`: https://github.com/actions? It seems most of the 'official' actions live there, and I think this would make a good addition there!

I also thought I'd ask in this ticket - what was the motivation behind using docker/python? Most of the major/official actions seem to use typescript, and I think many people are very familiar with the syntax to reference an action like this:

```
uses: actions/checkout@v3
```

I've used GitHub actions for quite a few years and I honestly can say I've never seen this syntax, so it was a bit strange to me at first:

```
uses: docker://ghcr.io/github/stale_repos:v1
```

Certainly not saying anything is wrong, but curious to learn about why this path was taken for this action. It seems like there is more complexity with making/pushing a docker image that gets referenced instead of just referencing a GitHub repo directly. It also seems a bit strange to me that an official GitHub action is using a 3rd party python library for GitHub instead of something like [octokit](https://github.com/octokit).

Thanks in advance!

**Comment by zkoppert** [comment]
👋🏻 Thanks for the questions! We put this in the github repo instead of in the actions repo because of the team that created and maintains it. It was created by the GitHub OSPO and the GitHub actions team manages the actions org. That being said, I take your point that maybe it belongs in the actions org. I can chat with those folks and see if they want it over there!

Using Docker and Python was a choice I made because I am much more familiar with those tools. I've done a little javascript and typescript and found debugging to be pretty difficult for me which made maintaining those repositories quite a chore. 😓 

It is definitely a more paved path for actions to use typescript and then reference the action directly, so I understand the raised eyebrows. I would guess that taking docker out of the equation would also make the action more performant, which probably doesn't matter for what this action does but interesting (to me) to note.

Given that choice of using python, I was stuck with going with a 3rd party python library since octokit does not have python support.

Hope that all makes sense!

**Comment by ahatzz11** [comment]
@zkoppert Thanks for the response! All of that definitely makes sense. From an outside perspective, it is definitely nice to see consistency in location, technology, and implementation of actions, especially when they come directly from the company that created Actions! Ideally there would be some collaboration between OSPO and the Actions team when it comes to OSS actions from GitHub - I would imagine most outside users don't really differentiate specific teams within GitHub. I own the implementation/support for Actions in an organization of ~250 engineers and I know that when there are weird differences it can often confuse people. I think that would be a few orders of magnitude larger for GitHub itself. 

Hopefully some of this can help steer this towards the more 'standard' GitHub Actions path, but implementation aside the functionality of this action is awesome - definitely something we love to track in our organization. Thanks again for the thorough response!
